version: "3.9"
services:
  go-websocket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-websocket
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
      - "${WS_PORT}:${WS_PORT}"
    volumes:
      - .env:/.env